import type { CameraBookmark } from "../types/camera-types";

export const CAMERA_PRESETS: CameraBookmark[] = [
  {
    id: "preset-aerial",
    name: "Aerial Perspective",
    description: "Full bird's-eye architectural view of parcel boundary and tower envelope.",
    position: [60, 65, 75],
    target: [0, 25, 0],
    fov: 45,
    isOrtho: false,
    thumbnailColor: "#3b82f6",
  },
  {
    id: "preset-street",
    name: "Street Level Human View",
    description: "Ground pedestrian perspective from access road easement.",
    position: [28, 2.5, 32],
    target: [0, 15, 0],
    fov: 55,
    isOrtho: false,
    thumbnailColor: "#10b981",
  },
  {
    id: "preset-south-elevation",
    name: "South Elevation (Ortho)",
    description: "True orthographic architectural front elevation.",
    position: [0, 27, 85],
    target: [0, 27, 0],
    fov: 35,
    isOrtho: true,
    thumbnailColor: "#f59e0b",
  },
  {
    id: "preset-north-elevation",
    name: "North Elevation (Ortho)",
    description: "Rear boundary orthographic survey alignment view.",
    position: [0, 27, -85],
    target: [0, 27, 0],
    fov: 35,
    isOrtho: true,
    thumbnailColor: "#8b5cf6",
  },
  {
    id: "preset-floor-5",
    name: "Target Floor 5 (Unit 502)",
    description: "Zoomed focus on target strata unit and floor slab.",
    position: [24, 32, 24],
    target: [0, 26.5, 0],
    fov: 40,
    isOrtho: false,
    thumbnailColor: "#06b6d4",
  },
];
