import type { GovernmentCase } from "../types/case-types";

export const SAMPLE_GOVERNMENT_CASES: GovernmentCase[] = [
  // 1. Mutation Transfer Application (Under Review)
  {
    id: "case-rev-01",
    caseNumber: "CASE-2024-MH-REV-0482",
    fileNumber: "FILE-ANDHERI-CTS-142/1-MUT",
    title: "Application for Form 6 Mutation (Joint Title Addition - Smt. Sunita Mehra)",
    caseType: "MUTATION_TRANSFER",
    currentDepartment: "REVENUE",
    currentAssigneeRole: "SUB_REGISTRAR",
    currentAssigneeName: "Anil Deshmukh (Sub-Registrar)",
    applicantName: "Rajiv M. Mehra & Sunita R. Mehra",
    applicantMaskedId: "PAN: ABCDE****F / AADHAAR: XXXX-XXXX-4821",
    priority: "MEDIUM",
    status: "UNDER_REVIEW",
    targetUlpin: "27518001004201-B01-TA-F05-U502",
    targetParcelId: "parcel-01",
    village: "Versova",
    surveyNumber: "CTS-142/1",
    filingDate: "01-Sep-2026",
    statutoryDeadline: "16-Sep-2026",
    slaDaysRemaining: 13,
    isEscalated: false,
    notingSheet: [
      {
        id: "note-01",
        paragraphNumber: 1,
        authorName: "Ramesh Joshi (Revenue Clerk)",
        authorRole: "SUB_REGISTRAR",
        department: "REVENUE",
        remarks:
          "Application received along with registered Gift Deed #4412/2026. Treasury Challan GRAS-8814 verified against state revenue portal. Transferred for verification.",
        timestamp: "01-Sep-2026 11:30:15",
        actionTaken: "NOTE",
      },
      {
        id: "note-02",
        paragraphNumber: 2,
        authorName: "Anil Deshmukh (Sub-Registrar)",
        authorRole: "SUB_REGISTRAR",
        department: "REVENUE",
        remarks:
          "Parties physically appeared on 02-Sep-2026. Biometric verification completed. ULPIN 3D strata mapping matches approved MCGM building occupation plan. Recommended for approval.",
        timestamp: "02-Sep-2026 15:45:00",
        actionTaken: "NOTE",
        digitalSignatureHash: "SIG-GOV-REGISTRAR-e3b0c44298fc1c149afbf4c8996fb92427ae41e4",
      },
    ],
    attachments: [
      {
        id: "att-01",
        name: "Registered_Gift_Deed_4412.pdf",
        type: "PDF",
        size: "2.4 MB",
        uploadDate: "01-Sep-2026",
        sha256Hash: "8f481c039db79f6eb3907c0eeec50438cf15a31e8acfe40c49740529cc55c0e7",
      },
      {
        id: "att-02",
        name: "Form_7_12_Extract_Versova.pdf",
        type: "PDF",
        size: "1.1 MB",
        uploadDate: "01-Sep-2026",
        sha256Hash: "a9d3e5f2142e03b30d8ffbbca834bcde107380927e1634b07c89f5bc39478f21",
      },
    ],
  },

  // 2. Boundary Survey Demarcation (Nearing SLA Limit)
  {
    id: "case-srv-02",
    caseNumber: "CASE-2024-MH-SRV-1094",
    fileNumber: "FILE-VERSOVA-CTS-142/P401A",
    title: "Petition for Boundary Demarcation & Survey of India CORS Tie-in",
    caseType: "BOUNDARY_SURVEY",
    currentDepartment: "SURVEY",
    currentAssigneeRole: "QA_OFFICER",
    currentAssigneeName: "Kavita Rao (District QA Officer)",
    applicantName: "Palm Heights Co-operative Housing Society",
    applicantMaskedId: "REG: MUM-BOM-HSG-4812",
    priority: "HIGH",
    status: "INSPECTION_ORDERED",
    targetUlpin: "27518001004201",
    targetParcelId: "parcel-01",
    village: "Versova",
    surveyNumber: "CTS-142",
    filingDate: "28-Aug-2026",
    statutoryDeadline: "04-Sep-2026",
    slaDaysRemaining: 1, // Warning!
    isEscalated: false,
    notingSheet: [
      {
        id: "note-03",
        paragraphNumber: 1,
        authorName: "Vikram Deshmukh (Survey Officer)",
        authorRole: "SURVEY_OFFICER",
        department: "SURVEY",
        remarks:
          "Field rover mission SM-2024-MH-401 completed on 03-Sep-2026. 4 corner markers (CP-1 to CP-4) recorded with Trimble R12i GNSS. Horizontal precision 1.4 cm. Forwarded to District QA.",
        timestamp: "03-Sep-2026 12:15:00",
        actionTaken: "FORWARD",
        forwardedToDepartment: "SURVEY",
        forwardedToRole: "QA_OFFICER",
      },
    ],
    attachments: [
      {
        id: "att-03",
        name: "DGPS_Field_Survey_Report_SM401.pdf",
        type: "PDF",
        size: "4.8 MB",
        uploadDate: "03-Sep-2026",
        sha256Hash: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
      },
    ],
  },

  // 3. High Court Contested Easement (Overdue & Auto-Escalated)
  {
    id: "case-dsp-03",
    caseNumber: "CASE-2024-MH-DSP-0082",
    fileNumber: "FILE-VERSOVA-CTS-144A-EASEMENT",
    title: "High Court Order: Disputed Western Road Easement Demarcation",
    caseType: "BOUNDARY_DISPUTE",
    currentDepartment: "REVENUE",
    currentAssigneeRole: "DISTRICT_COLLECTOR",
    currentAssigneeName: "Sanjay G. (District Collector)",
    applicantName: "High Court of Bombay (Writ Petition #841/2026)",
    applicantMaskedId: "WP: 841/2026 (OS)",
    priority: "EMERGENCY",
    status: "ASSIGNED",
    targetUlpin: "27518001004204",
    targetParcelId: "parcel-04",
    village: "Versova",
    surveyNumber: "CTS-144/A",
    filingDate: "12-Aug-2026",
    statutoryDeadline: "26-Aug-2026",
    slaDaysRemaining: -8, // Breached SLA!
    isEscalated: true,
    escalationReason: "Statutory 14-day SLA expired. Auto-escalated to District Collector.",
    notingSheet: [
      {
        id: "note-04",
        paragraphNumber: 1,
        authorName: "System SLA Engine",
        authorRole: "TEHSILDAR",
        department: "REVENUE",
        remarks:
          "SLA breach alert: Case pending beyond 14 statutory days under Maharashtra Right to Public Services Act. Automated escalation triggered to District Collector.",
        timestamp: "27-Aug-2026 00:01:00",
        actionTaken: "ESCALATE",
        forwardedToRole: "DISTRICT_COLLECTOR",
      },
    ],
    attachments: [
      {
        id: "att-04",
        name: "Bombay_HC_Order_WP841.pdf",
        type: "PDF",
        size: "1.8 MB",
        uploadDate: "12-Aug-2026",
        sha256Hash: "4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a",
      },
    ],
  },

  // 4. Commercial Subdivision ULPIN Issuance (Approved & Completed)
  {
    id: "case-ulp-04",
    caseNumber: "CASE-2024-MH-ULP-3810",
    fileNumber: "FILE-ANDHERI-GODREJ-CTS142/2",
    title: "Commercial Development Subdivision ULPIN Issuance",
    caseType: "ULPIN_ISSUANCE",
    currentDepartment: "REVENUE",
    currentAssigneeRole: "TEHSILDAR",
    currentAssigneeName: "Sunil Wankhede (Tehsildar)",
    applicantName: "Godrej Properties Dev. Ltd.",
    applicantMaskedId: "CIN: L45200MH1985PLC038005",
    priority: "LOW",
    status: "APPROVED",
    targetUlpin: "27518001004202",
    targetParcelId: "parcel-02",
    village: "Versova",
    surveyNumber: "CTS-142/2",
    filingDate: "15-Aug-2026",
    statutoryDeadline: "18-Aug-2026",
    slaDaysRemaining: 0,
    isEscalated: false,
    notingSheet: [
      {
        id: "note-05",
        paragraphNumber: 1,
        authorName: "Sunil Wankhede (Tehsildar)",
        authorRole: "TEHSILDAR",
        department: "REVENUE",
        remarks:
          "Approved Bhu-Aadhaar ULPIN 27518001004202 issued for 2,850 m² commercial parcel CTS-142/2. Certificate sealed.",
        timestamp: "18-Aug-2026 16:20:00",
        actionTaken: "APPROVE",
        digitalSignatureHash: "SIG-GOV-TEHSILDAR-8f481c039db79f6eb3907c0eeec50438cf15a31e",
      },
    ],
    attachments: [],
  },
];
