import type { AdministrativeNode } from "../types/hierarchy-types";

export const SAMPLE_HIERARCHY_TREE: AdministrativeNode[] = [
  {
    id: "node-india",
    level: "COUNTRY",
    code: "IND",
    name: "Republic of India",
    childrenCount: 28,
    metadata: {
      censusCode: "00",
      totalAreaHectares: 328726300,
      population: 1420000000,
    },
  },
  {
    id: "node-mh",
    level: "STATE",
    code: "27",
    name: "Maharashtra",
    parentId: "node-india",
    childrenCount: 36,
    metadata: {
      lgdCode: "LGD-STATE-27",
      censusCode: "27",
      stateCode: "MH",
      totalAreaHectares: 30771300,
      population: 125000000,
    },
  },
  {
    id: "node-mum-sub",
    level: "DISTRICT",
    code: "518",
    name: "Mumbai Suburban",
    parentId: "node-mh",
    childrenCount: 3,
    metadata: {
      lgdCode: "LGD-DIST-518",
      stateCode: "MH",
      districtCode: "518",
      totalAreaHectares: 44600,
      population: 9350000,
    },
  },
  {
    id: "node-andheri",
    level: "TALUKA",
    code: "4182",
    name: "Andheri (Tehsil / Sub-District)",
    parentId: "node-mum-sub",
    childrenCount: 14,
    metadata: {
      lgdCode: "LGD-TAL-4182",
      stateCode: "MH",
      districtCode: "518",
      totalAreaHectares: 12500,
      population: 3200000,
    },
  },
  {
    id: "node-versova",
    level: "VILLAGE",
    code: "554210",
    name: "Versova Revenue Village",
    parentId: "node-andheri",
    childrenCount: 8,
    metadata: {
      lgdCode: "LGD-VIL-554210",
      stateCode: "MH",
      districtCode: "518",
      totalAreaHectares: 480,
      population: 185000,
    },
  },
  {
    id: "node-ward-kw",
    level: "WARD",
    code: "MCGM-KW",
    name: "Ward K-West (Municipal Jurisdiction)",
    parentId: "node-versova",
    childrenCount: 22,
    metadata: {
      lgdCode: "MCGM-KW",
      stateCode: "MH",
      districtCode: "518",
    },
  },
  {
    id: "node-cts-142",
    level: "SURVEY_NUMBER",
    code: "CTS-142",
    name: "City Survey Number CTS-142",
    parentId: "node-ward-kw",
    childrenCount: 3,
    metadata: {
      totalAreaHectares: 2.85,
    },
  },
  {
    id: "node-subdiv-1",
    level: "SUBDIVISION",
    code: "HISSA-01",
    name: "Subdivision Hissa 1",
    parentId: "node-cts-142",
    childrenCount: 1,
    metadata: {
      totalAreaHectares: 0.142,
    },
  },
  {
    id: "node-parcel-401a",
    level: "PARCEL",
    code: "P-401/A",
    name: "Cadastral Parcel P-401/A (1,420 m²)",
    parentId: "node-subdiv-1",
    childrenCount: 1,
    metadata: {
      ulpinCode: "27518001004201",
      totalAreaHectares: 0.142,
    },
  },
  {
    id: "node-bldg-palm",
    level: "BUILDING",
    code: "BLDG-PALM-T1",
    name: "Palm Heights Tower 1",
    parentId: "node-parcel-401a",
    childrenCount: 18,
    metadata: {
      verticalFloorIndex: 18,
    },
  },
  {
    id: "node-floor-5",
    level: "FLOOR",
    code: "FLR-05",
    name: "Floor Level 5 (Elevation 42.5m AMSL)",
    parentId: "node-bldg-palm",
    childrenCount: 4,
    metadata: {
      verticalFloorIndex: 5,
    },
  },
  {
    id: "node-unit-502",
    level: "UNIT",
    code: "UNIT-502",
    name: "Strata Unit 502 (3D ULPIN: 27518001004201-F05-U502)",
    parentId: "node-floor-5",
    childrenCount: 0,
    metadata: {
      ulpinCode: "27518001004201-F05-U502",
      unitNumber: "502",
    },
  },
];
